dir("C:\\Users\\Kento\\Desktop","csv$")
nd <- read.csv("C:\\Users\\Kento\\Desktop\\all[kmatsui_nexus7-2012-hmurakami][kmatsui_nexus7-2013-haida]20160713143405.csv",header=T)
data <- subset(nd, class=="hide" | class=="slash" | class=="roll" | class=="up" | class=="down", select=c(1:6))
g <- as.matrix(subset(nd, class=="hide" | class=="slash" | class=="roll" | class=="up" | class=="down", select=7))
result.cv<-lda(data, g, CV=T)
library(MASS)
result.cv<-lda(data, g, CV=T)
(lda.tab<- table(nd[,7],result.cv$class))
result.cv
(lda.tab<- table(nd[,7],result.cv$class))
library(rpart)
nt <-rpart(class~., data=nd)
par(xpd = NA)
plot(nt, uniform=TRUE)
text(nt, use.n=TRUE, all=TRUE )
nt
printcp(nt)

sumary(hide)
summary(hide)
summary(nt)
plot(nt, uniform=TRUE)
text(nt, use.n=TRUE, all=TRUE )
plot(nt, uniform=TRUE)
text(nt, use.n=TRUE)
nt
plot(nt, uniform=TRUE)
text(nt)
plot(nt)
text(nt)
plot(nt)
text(nt,use.n=TRUE, all=TRUE)
plot(nt)
text(nt,use.n=TRUE)
plot(nt)
plot(nt, uniform=T, margin=0.05)
text(nt,use.n=TRUE)
plot(nt, margin=0.05)
text(nt,use.n=TRUE)
plot(nt, margin=0.2)
text(nt,use.n=TRUE)
plot(nt, uniform=T, margin=0.2)
text(nt,use.n=TRUE)
plot(nt, margin=0.2)
text(nt,use.n=TRUE)
q()
