dir("K:\\github\\MultiHandGesture\\R","csv$")
nd <- read.csv("K:\\github\\MultiHandGesture\\R\\all20160715195743.csv",header=T)
data <- subset(nd, class=="hide" | class=="slash" | class=="roll" | class=="up" | class=="down", select=c(1:4))
g <- as.matrix(subset(nd, class=="hide" | class=="slash" | class=="roll" | class=="up" | class=="down", select=5))
result.cv<-lda(data, g, CV=T)
result.cv
library(MASS)
result.cv<-lda(data, g, CV=T)
(lda.tab<- table(nd[,5],result.cv$class))
result.cv
(lda.tab<- table(nd[,5],result.cv$class))
library(rpart)
nt <-rpart(class~., data=nd)
par(xpd = NA)
plot(nt, uniform=TRUE)
text(nt, use.n=TRUE, all=TRUE )
nt
printcp(nt)

sumary(hide)
summary(hide)
summary(nt)
plot(nt, uniform=TRUE)
text(nt, use.n=TRUE, all=TRUE )
plot(nt, uniform=TRUE)
text(nt, use.n=TRUE)
nt
plot(nt, uniform=TRUE)
text(nt)
plot(nt)
text(nt)
plot(nt)
text(nt,use.n=TRUE, all=TRUE)
plot(nt)
text(nt,use.n=TRUE)
plot(nt)
plot(nt, uniform=T, margin=0.05)
text(nt,use.n=TRUE)
plot(nt, margin=0.05)
text(nt,use.n=TRUE)
plot(nt, margin=0.2)
text(nt,use.n=TRUE)
plot(nt, uniform=T, margin=0.2)
text(nt,use.n=TRUE)
plot(nt, margin=0.2)
text(nt,use.n=TRUE)
q()
